default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['TESOURO_DATABASE_USERNAME'] %>
  password: <%= ENV['TESOURO_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['TESOURO_DATABASE_HOST'] %>

development:
  <<: *default
  database: tesouro_development

production:
  <<: *default
  database: tesouro_production
